import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kevin Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className='font-bold text-6xl mt-40 text-center '>Hello World ! <a className='underline decoration-sky-500 text-zinc-50'>I am Kevin</a> and this is my first steps with <a className='underline decoration-purple-500 text-zinc-50'>NextJS</a> and <span className='underline decoration-pink-500 text-zinc-50'>TailwindCSS</span></h1>
      </main>
    </>
  )
}
